---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  nginx:
    build:
      context: ../backend/frontend-component-collection
      dockerfile: frontend-component-collection.Dockerfile
    container_name: frontend-component-collection
    restart: unless-stopped
    volumes:
      - ../frontend/frontend-component-collection/dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.frontend-component-collection.entrypoints=web
      - traefik.http.routers.frontend-component-collection.middlewares=test-redirectscheme
      - traefik.http.routers.frontend-component-collection-secure.entrypoints=websecure
      - traefik.http.routers.frontend-component-collection-secure.tls.certresolver=myresolver
      - traefik.http.routers.frontend-component-collection-secure.tls=true
      - traefik.http.routers.frontend-component-collection-secure.middlewares=test-compress,test-redirectscheme
      # Services
      - traefik.http.services.frontend-component-collection-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
